# Generated by Django 5.0.6 on 2024-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_remove_customer_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
