# Generated by Django 5.0.6 on 2024-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_customer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='customers/images/default.jpg', upload_to='customers/images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
