# Generated by Django 4.2.13 on 2024-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_customer_image_alter_customer_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='xyz street', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='New York', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='ABC DEF', max_length=20),
        ),
    ]
