# Generated by Django 5.0.6 on 2024-07-11 13:32

import landingPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_product_brand_product_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[landingPage.models.validate_rating]),
        ),
    ]
