# Generated by Django 5.0.6 on 2024-07-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0005_customer_address_customer_city_customer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
    ]
