# Generated by Django 5.0.6 on 2024-07-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landingPage", "0007_customer_is_active_customer_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="landingPage.category",
            ),
        ),
    ]
