# Generated by Django 5.0.6 on 2024-07-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0005_alter_product_description_alter_product_rating'),
        ('landingPage', '0007_customer_is_active_customer_is_admin_and_more'),
    ]

    operations = [
    ]
