# Generated by Django 5.0.6 on 2024-07-15 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landingPage", "0011_category_parent_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
