# Generated by Django 5.0.6 on 2024-07-15 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landingPage", "0015_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categorys"},
        ),
    ]
