# Generated by Django 5.0.6 on 2024-07-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "landingPage",
            "0018_alter_category_options_order_city_order_country_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="payment_method",
            new_name="province",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping",
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
    ]
